/**
 * Database type definitions for Supabase
 * 
 * This file will be auto-generated by Supabase CLI when you run:
 * npx supabase gen types typescript --local > lib/supabase/database.types.ts
 * 
 * For now, this is a placeholder with basic types.
 * Update this after running the type generation command.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      ver_profiles: {
        Row: {
          id: string
          email: string
          role: 'staff' | 'verifier' | 'chief_registrar' | 'admin'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          role?: 'staff' | 'verifier' | 'chief_registrar' | 'admin'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          role?: 'staff' | 'verifier' | 'chief_registrar' | 'admin'
          created_at?: string
          updated_at?: string
        }
      }
      // Add other table types as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'staff' | 'verifier' | 'chief_registrar' | 'admin'
      document_status: 'pending' | 'hashed' | 'verified' | 'rejected' | 'flagged'
      verification_status: 'verified' | 'rejected'
      action_type: 'upload' | 'hash' | 'verify' | 'delete' | 'export' | 'login' | 'logout' | 'update' | 'create'
    }
  }
}
